spring:
  application:
    name: "order-service"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    sasl.username: ${KAFKA_SASL_USERNAME}
    sasl.password: ${KAFKA_SASL_PASSWORD}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}

  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: never

springdoc:
  use-fqn: true

server:
  port: ${SERVER_PORT}

service:
  user:
    url: ${USER_SERVICE_URL}
  product:
    url: ${PRODUCT_SERVICE_URL}
  order:
    url: ${ORDER_SERVICE_URL}
  payment:
    url: ${PAYMENT_SERVICE_URL}
